@startuml

title klassediagram Marios Pizzabar


hide circle

Class MenuKort{
List<Pizza>
showMenu()
readMenuFromFile()
}

Class Pizza{
nr
navn
ingredienser
pris
}

Class OrderLine{
pizza
antal
}

Class Order{
list<OrderLine>
afhentningsTid
bestillingsTId
leveringsstatus
orderId
addOrderLine()
}

Class OrderList{
List<Order>
addOrder()
deliverOrder()
deleteOrder()
showOrders()
Statistik()...
saveOrderList()
}

Class OrderQueue{
Liste <!leveret Order>
Liste fast leveringstid
kø flydende leveringstid
splitQueue()
sortQueue()
showQueue()
}

MenuKort "1" -- "*" Pizza
Pizza "1" -- "*" OrderLine

OrderQueue "1" -down- "1" OrderList
OrderLine "*" -right- "1" Order
Order "*" -right- "1" OrderList

@enduml