@startuml

title domæneModel


hide circle
hide methods


Class MenuKort{
List<Pizza>
}

Class Pizza{
nr
navn
ingredienser
pris
}

Class OrderLine{
Pizza
antal
}

Class Order{
List af orderLine
bestillingsTId
afhentningsTid
pris
leveringsstatus

}

Class OrderQueue{
Liste af leveret=false ordre
sorteret i:
Liste af fast leveringstidspunkt
Liste uden fast leveringstidspunkt
}

Class OrderList{
Liste af ordre

}

MenuKort "1" -right- "*" Pizza
Pizza "1" -- "*" OrderLine

OrderLine "*"-right-"1" Order
Order "*" -- "1" OrderList
OrderList "*" -left- "1" OrderQueue

@enduml